<Project>
  <PropertyGroup>
    <ValheimGamePath>C:\Program Files (x86)\Steam\steamapps\common\Valheim</ValheimGamePath>
    <R2ModPath>C:\Users\house\AppData\Roaming\r2modmanPlus-local\Valheim\profiles</R2ModPath>
    <GaleModPath>C:\Users\house\AppData\Roaming\com.kesomannen.gale\valheim\profiles</GaleModPath>
    <ProfileName>drakeTest</ProfileName>

    <!-- Gale is the active launcher for this machine. -->
    <BepInExPath>$(GaleModPath)\$(ProfileName)\BepInEx</BepInExPath>
    <BEPINEX_PATH>$(BepInExPath)</BEPINEX_PATH>
    <VALHEIM_INSTALL>$(ValheimGamePath)</VALHEIM_INSTALL>
    <CorlibPath>$(ValheimGamePath)\valheim_Data\Managed</CorlibPath>
    <PublicizedAssembliesPath>$(ValheimGamePath)\valheim_Data\Managed\publicized_assemblies</PublicizedAssembliesPath>

    <AfterTargets>Build</AfterTargets>
  </PropertyGroup>
</Project>
