<Project>
  <PropertyGroup>
    <ThunderstoreName>LockSmith</ThunderstoreName>
    <ThunderstoreAuthor>DrakeMods</ThunderstoreAuthor>
    <RootNamespace>LockSmith</RootNamespace>
    <AssemblyName>LockSmith</AssemblyName>
    <Version>0.3.6</Version>
    <BepInPluginName>LockSmith</BepInPluginName>
    <BepInGuid>com.drakesworkshop.locksmith</BepInGuid>
    <ModInfoClass>LockSmith</ModInfoClass>
    <Description>Designate chests and doors with a Locksmith key. Public/private in wards, Personal/Team private chests, guests. Requires DrakeModsLibs.</Description>
    <WebsiteUrl>https://github.com/drakethos/LockSmith</WebsiteUrl>
    <DeployAfterTargets>CopyArtItemsToOutput</DeployAfterTargets>
  </PropertyGroup>
  <ItemGroup>
    <ThunderstoreDependency Include="denikson-BepInExPack_Valheim-5.4.2350" />
    <ThunderstoreDependency Include="ValheimModding-Jotunn-2.30.0" />
    <ThunderstoreDependency Include="DrakeMods-DrakeModsLibs-0.9.1" />
  </ItemGroup>
</Project>
