<Project>
  <PropertyGroup>
    <ThunderstoreName>LockSmith</ThunderstoreName>
    <ThunderstoreAuthor>DrakeMods</ThunderstoreAuthor>
    <RootNamespace>LockSmith</RootNamespace>
    <AssemblyName>LockSmith</AssemblyName>
    <Version>0.3.6</Version>
    <BepInPluginName>LockSmith</BepInPluginName>
    <BepInGuid>com.drakesworkshop.locksmith</BepInGuid>
    <ModInfoClass>LockSmith</ModInfoClass>
    <Description>Share chests and doors behind your ward without putting people on the ward. Designate a piece with the Locksmith key, then open it publicly or grant guest access to individuals. Also covers Personal/Team private chests for shared stashes.</Description>
    <WebsiteUrl>https://github.com/drakethos/LockSmith</WebsiteUrl>
    <DeployAfterTargets>CopyArtItemsToOutput</DeployAfterTargets>
  </PropertyGroup>
  <ItemGroup>
    <ThunderstoreDependency Include="denikson-BepInExPack_Valheim-5.4.2350" />
    <ThunderstoreDependency Include="ValheimModding-Jotunn-2.30.0" />
    <ThunderstoreDependency Include="DrakeMods-DrakeModsLibs-0.9.2" />
  </ItemGroup>
</Project>
